dist: xenial
language: python
python: 3.7
env:
  - PIPENV_VERBOSITY=-1
services: postgresql
before_install:
  - psql -d postgres -U postgres -c "SELECT version() as PostgreSQL_VERSION;"
  - psql -d postgres -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part1.sql
  - psql -d integration_test_db -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part2.sql
install: make install_deps
script:
  - make test_unit
  - make test_integration
  - make test_downgrade_schema
