dist: xenial
language: python
python: 3.7
env:
  - PIPENV_VERBOSITY=-1

services: docker
before_install:
  - docker pull postgres
  - docker run -p 5432:5432 -e POSTGRES_PASSWORD=travisci -d postgres
  - docker run psql -d postgres -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part1.sql
  - docker run psql -d integration_test_db -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part2.sql

install: make install_deps
script:
  - make test_unit
  - make test_integration
  - make test_downgrade_schema
