dist: xenial
language: python
python: 3.7
env:
  - PIPENV_VERBOSITY=-1
services: postgresql
before_install:
  - psql -d postgres -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part1.sql
install: make install_deps
before_script:
  - psql -d postgres -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part2.sql
script:
  - make test_unit
  - make test_integration
  - make test_downgrade_schema
