dist: xenial
language: python
python: 3.7
addons:
  postgresql: "11.3"
env:
  - PIPENV_VERBOSITY=-1
services: postgres
install: make install_deps
before_script:
 - psql -d postgres -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part1.sql
 - psql -d integration_test_db -U postgres -a -v ON_ERROR_STOP=1 -f ./tests/integration/setup-part2.sql
script:
  - make test_unit
  - make test_integration
  - make test_downgrade_schema
